#goal definition
string action
string boxId
string objId
string planGroup
geometry_msgs/PoseStamped pose
---
#result definition
moveit_msgs/MoveItErrorCodes error_code
int32 cost
---
#feedback
int32 status